---
- name: Get all hosts from vCenter
  hosts: localhost
  gather_facts: true
  collections:
    - vmware.vmware_rest
    - community.vmware
  vars:
    - vcenter_hostname: ""
    - vcenter_username: ""
    - vcenter_password: ""
    - vcenter_validate_certs: false
  tasks:
    - name: Get a list of the hosts
      vmware.vmware_rest.vcenter_host_info:
        vcenter_hostname: "{{ vcenter_hostname }}"
        vcenter_username: "{{ vcenter_username }}"
        vcenter_password: "{{ vcenter_password }}"
        vcenter_validate_certs: "{{ vcenter_validate_certs }}"
      register: vmware_hosts
      
    - name: Extract hostnames
      ansible.builtin.set_fact:
        esxi_hosts: "{{ vmware_hosts.value | map(attribute='name') | list }}"
    
    - name: Print all ESXi hosts
      ansible.builtin.debug:
        msg: "{{ esxi_hosts }}"
    
    - name: Enable SSH on ESXi hosts
      community.vmware.vmware_host_service_manager:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        esxi_hostname: "{{ item }}"
        service_name: "TSM-SSH"
        state: "start"
        service_policy: "automatic"
        validate_certs: false
      loop: "{{ esxi_hosts }}"
